services:
  client:
    build: client
    command: tail -f /dev/null
    volumes:
      - ./client/dns_client.py:/usr/local/ScapyClient/dns_client.py
    networks:
      scapy_dns_net:
        ipv4_address: 10.10.2.2
  
  authority:
    build: authority
    volumes:
      - ./authority/dns_auth.py:/usr/local/ScapyAuth/dns_auth.py
    privileged: true
    networks:
      scapy_dns_net:
        ipv4_address: 10.10.2.3
        
  unbound:
    build: unbound
    volumes:
      - ./unbound/keytrap.test.key:/usr/local/etc/unbound/keytrap.test.key
      - ./unbound/unbound.conf:/usr/local/etc/unbound/unbound.conf
    networks:
      scapy_dns_net:
        ipv4_address: 10.10.2.4
        
networks:
  scapy_dns_net:
    ipam:
      config:
        - subnet: 10.10.2.0/24

