services:
  attacker:
    build: ./client
    networks:
      app_net:
        ipv4_address: 10.10.0.2

  resolver:
    build: ./resolver
    networks:
      app_net:
        ipv4_address: 10.10.0.3

  auth:
    build: ./attacker
    networks:
      app_net:
        ipv4_address: 10.10.0.4

networks:
  app_net:
    ipam:
      config:
        - subnet: 10.10.0.0/24

