services:
  unbound:
    build: unbound
    volumes:
      - ./unbound/keytrap.test.key:/usr/local/etc/unbound/keytrap.test.key
      - ./unbound/unbound.conf:/usr/local/etc/unbound/unbound.conf
    networks:
      resolver_test_net:
        ipv4_address: 10.8.8.3

networks:
  resolver_test_net:
    ipam:
      config:
        - subnet: 10.8.8.0/24

