services:
  attacker:
    build: attacker
    networks:
      resolver_test_net:
        ipv4_address: 10.8.8.2

  unbound:
    build: unbound
    volumes:
      - ./unbound/unbound.conf:/usr/local/etc/unbound/unbound.conf
    networks:
      resolver_test_net:
        ipv4_address: 10.8.8.3

  bind:
    build: bind
    volumes:
      - ./bind/conf/named:/etc/default/named
      - ./bind/conf/named.conf:/var/named/chroot/etc/named.conf
    networks:
      resolver_test_net:
        ipv4_address: 10.8.8.4
    
  knot:
    build: knot
    volumes:
      - ./knot/knot.conf:/etc/knot/knot.conf
    networks:
      resolver_test_net:
        ipv4_address: 10.8.8.5
    
  powerdns:
    build: powerdns
    volumes:
      - ./powerdns/pdns.conf:/etc/pdns/pdns.conf
    networks:
      resolver_test_net:
        ipv4_address: 10.8.8.6


networks:
  resolver_test_net:
    ipam:
      config:
        - subnet: 10.8.8.0/24

