services:
  client:
    build: client
    command: tail -f /dev/null
    volumes:
      - ./client/client.py:/usr/local/ScapyClient/client.py
    networks:
      go_dns_net:
        ipv4_address: 10.10.3.2
  
  authority:
    build: authority
    volumes:
      - ./authority/auth.go:/usr/local/GoDNS/auth.go
    privileged: true
    networks:
      go_dns_net:
        ipv4_address: 10.10.3.3
        
  unbound:
    build: unbound
    volumes:
      - ./anchor/test.key:/usr/local/etc/unbound/test.key
      - ./unbound/unbound.conf:/usr/local/etc/unbound/unbound.conf
    networks:
      go_dns_net:
        ipv4_address: 10.10.3.4

  bind:
    build: bind
    volumes:
      - ./bind/conf/named:/etc/default/named
      - ./bind/conf/named.conf:/var/named/chroot/etc/named.conf
      - ./bind/conf/named.log:/etc/named.log
    networks:
      go_dns_net:
        ipv4_address: 10.10.3.5

  knot:
    build: knot
    volumes:
      - ./knot/kresd.conf:/etc/knot/kresd.conf
    networks:
      go_dns_net:
        ipv4_address: 10.10.3.6
    
  powerdns:
    build: powerdns
    volumes:
      - ./anchor/test.key:/etc/pdns/test.key
      - ./powerdns/recursor.conf:/etc/pdns/recursor.conf
    networks:
      go_dns_net:
        ipv4_address: 10.10.3.7

networks:
  go_dns_net:
    ipam:
      config:
        - subnet: 10.10.3.0/24

