services:
  client:
    build: client
    command: tail -f /dev/null
    volumes:
      - ./client/dns_client.py:/usr/local/ScapyClient/dns_client.py
    networks:
      go_dns_net:
        ipv4_address: 10.10.3.2
  
  authority:
    build: authority
    volumes:
      - ./authority/dns_auth.go:/usr/local/GoDNS/dns_auth.z
      - ./authority/go.mod:/usr/local/GoDNS/go.mod
      - ./authority/go.sum:/usr/local/GoDNS/go.sum
    privileged: true
    networks:
      go_dns_net:
        ipv4_address: 10.10.3.3
        
  unbound:
    build: unbound
    volumes:
      - ./unbound/keytrap.test.key:/usr/local/etc/unbound/keytrap.test.key
      - ./unbound/unbound.conf:/usr/local/etc/unbound/unbound.conf
    networks:
      go_dns_net:
        ipv4_address: 10.10.3.4
        
networks:
  go_dns_net:
    ipam:
      config:
        - subnet: 10.10.3.0/24

