services:
  resolver:
    build: resolver
    volumes:
      - ./resolver/unbound.conf:/usr/local/etc/unbound/unbound.conf
      - ./resolver/test.key:/usr/local/etc/unbound/test.key
    networks:
      app_net:
        ipv4_address: 10.10.0.3

  root:
    build: root
    volumes:
      - ./root/conf/named:/etc/default/named
      - ./root/conf/named.conf:/var/named/chroot/etc/named.conf
      - ./root/datafile/test.zone.signed:/var/named/chroot/var/named/test.zone.signed
    networks:
      app_net:
        ipv4_address: 10.10.0.4

  auth:
    build: auth
    volumes:
      - ./auth/conf/named:/etc/default/named
      - ./auth/conf/named.conf:/var/named/chroot/etc/named.conf
      - ./auth/datafile/keytrap.test.zone.signed:/var/named/chroot/var/named/keytrap.test.zone.signed
    networks:
      app_net:
        ipv4_address: 10.10.0.5


  nxns:
    build: nxns
    volumes:
      - ./nxns/conf/named:/etc/default/named
      - ./nxns/conf/named.conf:/var/named/chroot/etc/named.conf
      - ./nxns/datafile/nxns.test.zone.signed:/var/named/chroot/var/named/nxns.test.zone.signed
    networks:
      app_net:
        ipv4_address: 10.10.0.6


networks:
  app_net:
    ipam:
      config:
        - subnet: 10.10.0.0/24

