services:
  client:
    build: client
    command: tail -f /dev/null
    volumes:
      - ./client/dns_client.py:/usr/local/ScapyClient/dns_client.py
    networks:
      test_net:
        ipv4_address: 10.10.0.2
    
  unbound:
    build: unbound
    volumes:
      - ./unbound/keytrap.test.key:/usr/local/etc/unbound/keytrap.test.key
      - ./unbound/unbound.conf:/usr/local/etc/unbound/unbound.conf
    networks:
      test_net:
        ipv4_address: 10.10.0.4

  authority:
    build: authority
    volumes:
      - ./authority/dns_auth.py:/usr/local/ScapyAuth/dns_auth.py
    privileged: true
    networks:
      test_net:
        ipv4_address: 10.10.0.3
        
networks:
  test_net:
    ipam:
      config:
        - subnet: 10.10.0.0/24

