services:
  attacker:
    build: sender
    command: tail -f /dev/null
    networks:
      app_net:
        ipv4_address: 10.10.0.2

  resolver:
    build: nameserver
    volumes:
      - ./resolver/unbound.conf:/usr/local/etc/unbound/unbound.conf
      - ./resolver/keytrap.test.key:/usr/local/etc/unbound/keytrap.test.key
      - ./resolver/nxns.test.key:/usr/local/etc/unbound/nxns.test.key
    networks:
      app_net:
        ipv4_address: 10.10.0.3

  auth:
    build: auth
    volumes:
      - ./auth/conf/named:/etc/default/named
      - ./auth/conf/named.conf:/var/named/chroot/etc/named.conf
      - ./auth/datafile/keytrap.test.zone.signed:/var/named/chroot/var/named/keytrap.test.zone.signed
    networks:
      app_net:
        ipv4_address: 10.10.0.4

networks:
  app_net:
    ipam:
      config:
        - subnet: 10.10.0.0/24

